#!/bin/bash -x
git clone https://github.com/giantswarm/kubernetes-elastic-stack.git /root/efk
cd /root/efk && kubectl apply --filename https://raw.githubusercontent.com/giantswarm/kubernetes-elastic-stack/master/manifests-all.yaml
sleep 120
cd /root/efk && kubectl port-forward $(kubectl get pods | grep kibana | cut -d' ' -f1) 5601:5601 &
exit 0
