#!/bin/bash
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x kubectl && mv kubectl /usr/local/bin/
echo 'export AWS_AVAILABILITY_ZONES="us-west-2a,us-west-2b,us-west-2c"' >> /root/.bash_profile
curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
chmod +x kops-linux-amd64
mv kops-linux-amd64 /usr/local/bin/kops
touch /root/.bash_profile
echo 'export HOME=/root' >> /root/.bash_profile
. /root/.bash_profile
echo 'export PATH=$PATH:$HOME:/usr/local/bin/' >> /root/.bash_profile
ssh-keygen -q -N '' -f /root/.ssh/id_rsa
echo 'export S3_BUCKET=kube-state-store-repo' >> /root/.bash_profile
echo 'export KOPS_STATE_STORE=s3://"$S3_BUCKET"' >> /root/.bash_profile
. /root/.bash_profile
aws s3 mb $KOPS_STATE_STORE
aws s3api put-bucket-versioning --bucket $S3_BUCKET --versioning-configuration Status=Enabled
kops create cluster --name private.cluster.k8s.local --master-count 3 --node-count 5 --zones $AWS_AVAILABILITY_ZONES --target=cloudformation --yes
